film/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('films/', views.film_list),
    path('films/<int:id>/', views.film_detail),
    path('genres/', views.genre_list),
    path('genres/<int:id>/', views.genre_detail),
]

movies/urls.py
from django.urls import path
from . import views
app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>', views.detail, name='detail')
]

vidly/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views

admin.site.site_header = 'Vidly Admin'
admin.site.index_title = 'Admin'
movie_resource = MovieResource()

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls)),
    path('playground/', include('playground.urls')),
    path('store/', include('store.urls')),
    path('film/', include('film.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

movies/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

movies/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from . models import Movie

# Create your views here.


def index(request):
    movies = Movie.objects.all()
    return render(request, 'movies/index.html', {'movies': movies})


def detail(request, movie_id):
    # try:
    #     movie = Movie.objects.get(pk=movie_id)
    #     return render(request, 'movies/detail.html', {'movie': movie})
    # except Movie.DoesNotExist:
    #     raise Http404()
    movie = get_object_or_404(Movie, pk=movie_id)
    return render(request, 'movies/detail.html', {'movie': movie})

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
<dl>
  <dt>Title</dt>
  <dd>{{movie.title}}</dd>
  <dt>Genre</dt>
  <dd>{{movie.genre}}</dd>
  <dt>Stock</dt>
  <dd>{{movie.number_in_stock}}</dd>
</dl>
{% endblock  %}

movies/templates/movies/index.html
{% extends 'base.html' %} {% block content %}
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Number In Stock</th>
      <th>Daily Rate</th>
      <th>Genre</th>
    </tr>
  </thead>
  <tbody>
    {% for movie in movies %}
    <tr>
      <td><a href="{% url "movies:detail" movie.id %}">{{ movie.title}}</a></td>
      <td>{{movie.number_in_stock}}</td>
      <td>{{movie.daily_rate}}</td>
      <td>{{movie.genre}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}